version: '3.8'
services:  
  postgresql:
    environment:
      - POSTGRES_USER=efficienttravel
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5432:5432"